version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - webnet

  frontend:
    build: ./mindbridgewebapp
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:

