version: "3.8"

services:
    web:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        ports:
            - "3001:3001"
        env_file:
            - ./backend/.env

    frontend:
        build:
            context: ./mindbridge
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
