version: "3.8"

services:
    web:
        build: ./backend
        ports:
            - "3001:3001"

    frontend:
        build:
            context: ./mindbridge
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
